### ISSUE TITLE
Cannot choose custom music for discs

### ISSUE THREAD

**Issue by codeoffun2** [legopitstop/Record_API#1]
Wheneveri select a new OGG file, the file does not get selected and is stuck on the default .ogg file.
 - Minecraft Version: 1.20.1

**Comment by legopitstop** [comment]
If you need to use Minecraft 1.20.1 you will need to use Record API v1.1.0 and App v0.0.1 as the API changes added in v1.2.0 only work on Minecraft 1.20.2.

**Comment by legopitstop** [comment]
Thank you for your report! Please make sure to include the following information;
1. Steps to reproduce the error
2. App version
3. Platform (Windows 11, MacOS, Linux, etc)
4. Record API version that you're using in-game

Please make these changes to this report and I will re-open it.
